guard 'remote-sync',
	:source => ".", 
	:destination => '/export/home/{username}/tmp', 
	:user => '{user}',
	:remote_address => '{address}',
	:verbose => true, 
	:cli => "--color", 
	:sync_on_start => true do
  
  watch(%r{^.+\.(js|xml|php|class|config)$})
end